# Generated by Django 4.2.1 on 2024-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.ImageField(upload_to='composer_images/'),
        ),
    ]
