# Generated by Django 4.2.1 on 2024-02-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_employees_photofilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Email',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
