# Generated by Django 4.2.1 on 2024-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration_time',
        ),
        migrations.AddField(
            model_name='event',
            name='duration_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
