# Generated by Django 4.2.1 on 2024-02-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_remove_event_duration_time_event_duration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('0', 'Without Duration'), ('1', 'Until')], max_length=20, null=True),
        ),
    ]
