# Generated by Django 4.2.1 on 2024-02-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_alter_event_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration_type',
            field=models.CharField(blank=True, choices=[(False, 'Without Duration'), (True, 'Until')], max_length=20, null=True),
        ),
    ]
