# Generated by Django 4.2.1 on 2024-02-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_alter_event_duration_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='duration_value',
            new_name='duration_time',
        ),
    ]
