# Generated by Django 4.2.1 on 2024-02-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0005_rename_duration_value_event_duration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration_type',
            field=models.BooleanField(choices=[(False, 'Without Duration'), (True, 'Until')], default=False),
        ),
    ]
