# Generated by Django 4.2.1 on 2024-02-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0007_alter_event_repeat_type_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration_type',
            field=models.BooleanField(blank=True, choices=[(False, 'Without Duration'), (True, 'Until')], default=False, null=True),
        ),
    ]
